const seed=[{house:"LA",preferredName:"Juliana",lastName:"Addison",electorate:"Wendouree",party:"Australian Labor Party",image:"AddisonJuliana_P.jpeg"}];
let members=JSON.parse(localStorage.getItem("vicparlMembers")||"null")||seed;
const app=document.querySelector("#app");
function home(){app.className="card";app.innerHTML=`<h2>Ready to begin</h2><p>Choose a mode above. Press Escape at any time to return here.</p>`}
document.addEventListener("keydown",e=>{if(e.key==="Escape")home()});
function imgPath(m){return `images/${m.house}/${m.image}`}
function start(mode){const m=members[Math.floor(Math.random()*members.length)];app.className=`card ${m.house.toLowerCase()}`;if(mode==="quiz"){app.innerHTML=`<h2>Who is this member?</h2><img class="member" src="${imgPath(m)}" alt="Member photograph" onerror="this.style.display='none'"><p><input id="answer" placeholder="Type the member's name"> <button onclick='check(${JSON.stringify(m)})'>Check</button></p><p id="feedback"></p>`}else{app.innerHTML=`<h2>${m.house==="LC"?"Legislative Council":"Legislative Assembly"}</h2><img class="member" src="${imgPath(m)}" alt="Member photograph" onerror="this.style.display='none'"><h3>${m.preferredName} ${m.lastName}</h3><p>${m.electorate} • ${m.party}</p><button onclick="start('flashcard')">Next member</button>`}}
function norm(s){return s.toLowerCase().replace(/[^a-z]/g,'')}
function check(m){const v=document.querySelector('#answer').value;const ok=norm(v)===norm(m.preferredName+m.lastName)||norm(v)===norm(m.lastName);document.querySelector('#feedback').textContent=ok?'Correct!':`Not quite. The answer is ${m.preferredName} ${m.lastName}.`}
function showAdmin(){app.className='card';app.innerHTML=`<h2>Admin: add a member</h2><p><select id="house"><option>LA</option><option>LC</option></select><input id="first" placeholder="Preferred name"><input id="last" placeholder="Last name"><input id="elect" placeholder="Electorate/region"><input id="party" placeholder="Party"><input id="image" placeholder="Image filename, e.g. AddisonJuliana_P.jpeg"></p><button onclick="saveMember()">Save member</button><p>${members.length} member record(s) currently stored in this browser.</p>`}
function saveMember(){const g=id=>document.querySelector('#'+id).value.trim();members.push({house:g('house'),preferredName:g('first'),lastName:g('last'),electorate:g('elect'),party:g('party'),image:g('image')});localStorage.setItem('vicparlMembers',JSON.stringify(members));showAdmin()}
