let members=[];
let progress=JSON.parse(localStorage.getItem('vicparlProgress')||'{}');
const stage=document.querySelector('#stage');let current=null,hintLevel=0,lastId=null;
const save=()=>localStorage.setItem('vicparlProgress',JSON.stringify(progress));
const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
const full=m=>`${m.preferredName} ${m.lastName}`;const placeLabel=m=>m.house==='LC'?'region':'electorate';
const imagePath=m=>`images/${m.house}/${encodeURIComponent(m.image).replace(/%2F/g,'/')}`;
function home(){stage.innerHTML=`<div class="panel"><h2>Ready to begin</h2><p>Choose a mode above. Press <kbd>Esc</kbd> at any time to return here.</p></div>`;current=null}
document.addEventListener('keydown',e=>{if(e.key==='Escape')home();if(e.key==='Enter'&&document.activeElement?.id==='answer'){document.querySelector('[data-check]')?.click()}});
function chamber(m){return `<div class="chamber">${m.house==='LC'?'LEGISLATIVE COUNCIL':'LEGISLATIVE ASSEMBLY'}</div>`}
function pkey(m,type){return `${m.id}:${type}`}
function difficulty(m,type){let p=progress[pkey(m,type)]||{tries:0,score:0};if(!p.tries)return 6;return Math.max(1,6-(p.score/Math.max(1,p.tries))*1.5)+Math.min(3,p.misses||0)}
function weighted(type){let candidates=members.filter(m=>m.id!==lastId);if(!candidates.length)candidates=members;let bag=[];for(const m of candidates){let w=Math.max(1,Math.round(difficulty(m,type)));for(let i=0;i<w;i++)bag.push(m)}let m=bag[Math.floor(Math.random()*bag.length)];lastId=m.id;return m}
function record(m,type,outcome){let k=pkey(m,type),p=progress[k]||{tries:0,score:0,hints:0,misses:0};p.tries++;if(outcome==='free')p.score+=3;if(outcome==='hint1')p.score+=2;if(outcome==='hint2')p.score+=1;if(outcome==='choice')p.score+=.5;if(outcome==='wrong'){p.score=Math.max(0,p.score-.5);p.misses++}else p.misses=Math.max(0,p.misses-1);if(['hint1','hint2','choice'].includes(outcome))p.hints++;p.last=Date.now();progress[k]=p;save()}
function nextBtn(fn){return `<button class="action" onclick="${fn}()">Next member</button>`}
function startFlashcards(){let m=weighted('study');stage.innerHTML=`<div class="panel ${m.house.toLowerCase()}">${chamber(m)}<img class="member" src="${imagePath(m)}" alt="${full(m)}"><h2>${full(m)}</h2><p><strong>${m.district}</strong><br>${m.party}</p>${nextBtn('startFlashcards')}</div>`}
function startNameQuiz(){current=weighted('name');hintLevel=0;renderName()}
function renderName(msg=''){let m=current;stage.innerHTML=`<div class="panel ${m.house.toLowerCase()}">${chamber(m)}<h2>Who is this?</h2><img class="member" src="${imagePath(m)}" alt="Member photograph"><input id="answer" autocomplete="off" placeholder="Type the member's name"><div><button class="action" data-check onclick="checkName()">Check</button><button class="action secondary" onclick="offerHint()">I don't know / Hint</button></div><p class="feedback">${msg}</p><div id="hint"></div></div>`;document.querySelector('#answer').focus()}
function nameCorrect(a,m){return a===norm(full(m))||a===norm(m.lastName)}
function checkName(){let a=norm(document.querySelector('#answer').value);if(nameCorrect(a,current)){record(current,'name',hintLevel===0?'free':hintLevel===1?'hint1':hintLevel===2?'hint2':'choice');document.querySelector('.feedback').textContent=`Correct. ${full(current)} represents ${current.district}.`;setTimeout(startNameQuiz,1300)}else{record(current,'name','wrong');document.querySelector('.feedback').textContent='Not quite. Try again, or ask for a hint.'}}
function offerHint(){hintLevel++;let h=document.querySelector('#hint');if(hintLevel===1)h.innerHTML=`<div class="hint"><strong>Hint:</strong> This member sits in the ${current.house==='LC'?'Legislative Council':'Legislative Assembly'}.</div>`;else if(hintLevel===2)h.innerHTML=`<div class="hint"><strong>Another hint:</strong> This member represents <strong>${current.district}</strong>.</div>`;else showNameChoices()}
function distractorsForName(){let pool=members.filter(m=>m.id!==current.id&&m.house===current.house);let sameDistrict=pool.filter(m=>m.district===current.district);let rest=pool.filter(m=>m.district!==current.district).sort(()=>Math.random()-.5);return [...sameDistrict.sort(()=>Math.random()-.5),...rest].slice(0,3)}
function showNameChoices(){hintLevel=3;let opts=[current,...distractorsForName()].sort(()=>Math.random()-.5);document.querySelector('#hint').innerHTML=`<div class="hint"><strong>Final hint: choose the member.</strong><div class="choices">${opts.map(m=>`<button onclick="chooseName('${m.id}')">${full(m)}</button>`).join('')}</div></div>`}
function chooseName(id){let ok=current.id===id;record(current,'name',ok?'choice':'wrong');document.querySelector('.feedback').textContent=ok?`Correct. This is ${full(current)}.`:`Not quite. This is ${full(current)}.`;setTimeout(startNameQuiz,1400)}
function startElectorateQuiz(){current=weighted('district');hintLevel=0;let m=current;stage.innerHTML=`<div class="panel ${m.house.toLowerCase()}">${chamber(m)}<h2>Which ${placeLabel(m)} does ${full(m)} represent?</h2><img class="member" src="${imagePath(m)}" alt="${full(m)}"><input id="answer" autocomplete="off" placeholder="Type ${placeLabel(m)}"><div><button class="action" data-check onclick="checkPlace()">Check</button><button class="action secondary" onclick="placeHint()">I don't know / Hint</button></div><p class="feedback"></p><div id="hint"></div></div>`;document.querySelector('#answer').focus()}
function checkPlace(){let ok=norm(document.querySelector('#answer').value)===norm(current.district);record(current,'district',ok?(hintLevel?'choice':'free'):'wrong');if(ok){document.querySelector('.feedback').textContent='Correct!';setTimeout(startElectorateQuiz,1100)}else document.querySelector('.feedback').textContent='Not quite. Try again, or ask for a hint.'}
function placeHint(){hintLevel=1;let pool=[...new Set(members.filter(x=>x.house===current.house&&x.district!==current.district).map(x=>x.district))].sort(()=>Math.random()-.5).slice(0,3);let opts=[current.district,...pool].sort(()=>Math.random()-.5);document.querySelector('#hint').innerHTML=`<div class="hint"><strong>Need some help? Choose an answer.</strong><div class="choices">${opts.map(x=>`<button onclick='choosePlace(${JSON.stringify(x)})'>${x}</button>`).join('')}</div></div>`}
function choosePlace(x){let ok=x===current.district;record(current,'district',ok?'choice':'wrong');document.querySelector('.feedback').textContent=ok?'Correct!':`Not quite. The answer is ${current.district}.`;setTimeout(startElectorateQuiz,1300)}
function summary(type){let ps=members.map(m=>progress[pkey(m,type)]).filter(Boolean);let practised=ps.length,strong=ps.filter(p=>p.tries>=2&&p.score/p.tries>=2.2).length,developing=ps.filter(p=>p.score/p.tries>=1&&!(p.tries>=2&&p.score/p.tries>=2.2)).length,learning=ps.filter(p=>p.score/p.tries<1).length;return{practised,strong,developing,learning}}
function showProgress(){let n=summary('name'),d=summary('district'),tries=Object.values(progress).reduce((a,p)=>a+p.tries,0);stage.innerHTML=`<div class="panel"><h2>My Progress</h2><p>${tries} total practice attempts saved in this browser.</p><div class="progress-grid"><div class="stat"><strong>Names</strong><p>Strong: ${n.strong}<br>Developing: ${n.developing}<br>Learning: ${n.learning}<br>Not yet practised: ${members.length-n.practised}</p></div><div class="stat"><strong>Electorates / regions</strong><p>Strong: ${d.strong}<br>Developing: ${d.developing}<br>Learning: ${d.learning}<br>Not yet practised: ${members.length-d.practised}</p></div></div><p><button class="action secondary" onclick="resetProgress()">Reset my progress</button></p></div>`}
function resetProgress(){if(confirm('Reset all saved quiz progress in this browser?')){progress={};save();showProgress()}}
function showAdmin(){stage.innerHTML=`<div class="panel"><h2>Admin</h2><p>The live member dataset is loaded from <code>members.json</code>.</p><p><strong>${members.length}</strong> current member records loaded: ${members.filter(m=>m.house==='LA').length} LA and ${members.filter(m=>m.house==='LC').length} LC.</p></div>`}
async function init(){try{let r=await fetch('members.json',{cache:'no-store'});if(!r.ok)throw new Error(r.status);members=await r.json();if(members.length!==128)throw new Error(`Expected 128 members, found ${members.length}`);home()}catch(e){stage.innerHTML=`<div class="panel"><h2>Member data could not be loaded</h2><p>Check that <code>members.json</code> is in the repository root, then refresh.</p><small>${e.message}</small></div>`}}
init();
