const seed=[{id:'addison-juliana',house:'LA',preferredName:'Juliana',lastName:'Addison',electorate:'Wendouree',party:'Australian Labor Party',image:'AddisonJuliana_P.jpeg'}];
let members=JSON.parse(localStorage.getItem('vicparlMembers')||'null')||seed;
let progress=JSON.parse(localStorage.getItem('vicparlProgress')||'{}');
const stage=document.querySelector('#stage');let current=null,hintLevel=0,attempted=false;
const save=()=>localStorage.setItem('vicparlProgress',JSON.stringify(progress));
const norm=s=>(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
const full=m=>`${m.preferredName} ${m.lastName}`;const placeLabel=m=>m.house==='LC'?'region':'electorate';
const imagePath=m=>`images/${m.house}/${m.image}`;
function home(){stage.innerHTML=`<div class="panel"><h2>Ready to begin</h2><p>Choose a mode above. Press <kbd>Esc</kbd> at any time to return here.</p></div>`;current=null}
document.addEventListener('keydown',e=>{if(e.key==='Escape')home()});
function chamber(m){return `<div class="chamber">${m.house==='LC'?'LEGISLATIVE COUNCIL':'LEGISLATIVE ASSEMBLY'}</div>`}
function weighted(type){return members[Math.floor(Math.random()*members.length)]}
function pkey(m,type){return `${m.id||norm(full(m))}:${type}`}
function record(m,type,outcome){let k=pkey(m,type),p=progress[k]||{tries:0,score:0,hints:0};p.tries++;if(outcome==='free')p.score+=3;if(outcome==='hint1')p.score+=2;if(outcome==='hint2')p.score+=1;if(outcome==='choice')p.score+=.5;if(outcome==='wrong')p.score=Math.max(0,p.score-.5);if(outcome.startsWith('hint')||outcome==='choice')p.hints++;progress[k]=p;save()}
function startFlashcards(){let m=weighted('study');stage.innerHTML=`<div class="panel ${m.house.toLowerCase()}">${chamber(m)}<img class="member" src="${imagePath(m)}" alt="${full(m)}"><h2>${full(m)}</h2><p><strong>${m.electorate}</strong><br>${m.party}</p><button class="action" onclick="startFlashcards()">Next member</button></div>`}
function startNameQuiz(){current=weighted('name');hintLevel=0;attempted=false;renderName()}
function renderName(msg=''){let m=current;stage.innerHTML=`<div class="panel ${m.house.toLowerCase()}">${chamber(m)}<h2>Who is this?</h2><img class="member" src="${imagePath(m)}" alt="Member photograph"><input id="answer" autocomplete="off" placeholder="Type the member's name"><div><button class="action" onclick="checkName()">Check</button><button class="action secondary" onclick="offerHint()">I don't know / Hint</button></div><p class="feedback">${msg}</p><div id="hint"></div></div>`;document.querySelector('#answer').focus()}
function checkName(){let a=norm(document.querySelector('#answer').value),target=norm(full(current));if(a===target||a===norm(current.lastName)){record(current,'name',hintLevel===0?'free':hintLevel===1?'hint1':hintLevel===2?'hint2':'choice');renderName(`Correct. ${full(current)} represents ${current.electorate}.`);setTimeout(startNameQuiz,1200)}else{attempted=true;record(current,'name','wrong');document.querySelector('.feedback').textContent='Not quite. Try again, or ask for a hint.'}}
function offerHint(){hintLevel++;let h=document.querySelector('#hint');if(hintLevel===1)h.innerHTML=`<div class="hint"><strong>Hint:</strong> This member sits in the ${current.house==='LC'?'Legislative Council':'Legislative Assembly'}.</div>`;else if(hintLevel===2)h.innerHTML=`<div class="hint"><strong>Another hint:</strong> This member represents <strong>${current.electorate}</strong>.</div>`;else showNameChoices()}
function showNameChoices(){hintLevel=3;let pool=[...members.filter(x=>x!==current)].sort(()=>Math.random()-.5).slice(0,3);let opts=[current,...pool].sort(()=>Math.random()-.5);document.querySelector('#hint').innerHTML=`<div class="hint"><strong>Final hint: choose the member.</strong><div class="choices">${opts.map(m=>`<button onclick="chooseName('${m.id||norm(full(m))}')">${full(m)}</button>`).join('')}</div></div>`}
function chooseName(id){let ok=(current.id||norm(full(current)))===id;record(current,'name',ok?'choice':'wrong');document.querySelector('.feedback').textContent=ok?`Correct. This is ${full(current)}.`:`Not quite. This is ${full(current)}.`;setTimeout(startNameQuiz,1400)}
function startElectorateQuiz(){current=weighted('electorate');hintLevel=0;let m=current;stage.innerHTML=`<div class="panel ${m.house.toLowerCase()}">${chamber(m)}<h2>Which ${placeLabel(m)} does ${full(m)} represent?</h2><img class="member" src="${imagePath(m)}" alt="${full(m)}"><input id="answer" autocomplete="off" placeholder="Type ${placeLabel(m)}"><div><button class="action" onclick="checkPlace()">Check</button><button class="action secondary" onclick="placeHint()">I don't know / Hint</button></div><p class="feedback"></p><div id="hint"></div></div>`;document.querySelector('#answer').focus()}
function checkPlace(){let ok=norm(document.querySelector('#answer').value)===norm(current.electorate);record(current,'electorate',ok?(hintLevel?'choice':'free'):'wrong');if(ok){document.querySelector('.feedback').textContent='Correct!';setTimeout(startElectorateQuiz,1000)}else document.querySelector('.feedback').textContent='Not quite. Try again, or ask for a hint.'}
function placeHint(){hintLevel=1;let uniq=[...new Set(members.filter(x=>x.house===current.house).map(x=>x.electorate).filter(Boolean))];let opts=[current.electorate,...uniq.filter(x=>x!==current.electorate).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5);document.querySelector('#hint').innerHTML=`<div class="hint"><strong>Need some help? Choose an answer.</strong><div class="choices">${opts.map(x=>`<button onclick="choosePlace(${JSON.stringify(x)})">${x}</button>`).join('')}</div></div>`}
function choosePlace(x){let ok=x===current.electorate;record(current,'electorate',ok?'choice':'wrong');document.querySelector('.feedback').textContent=ok?'Correct!':`Not quite. The answer is ${current.electorate}.`;setTimeout(startElectorateQuiz,1200)}
function showProgress(){let vals=Object.values(progress),tries=vals.reduce((a,p)=>a+p.tries,0),score=vals.reduce((a,p)=>a+p.score,0),assisted=vals.reduce((a,p)=>a+p.hints,0);let pct=tries?Math.min(100,Math.round(score/(tries*3)*100)):0;stage.innerHTML=`<div class="panel"><h2>My Progress</h2><div class="progress-grid"><div class="stat"><strong>Practice attempts</strong><h2>${tries}</h2></div><div class="stat"><strong>Unassisted strength</strong><h2>${pct}%</h2><div class="meter"><i style="width:${pct}%"></i></div></div><div class="stat"><strong>Hints used</strong><h2>${assisted}</h2></div><div class="stat"><strong>Saved locally</strong><p>Your progress remains in this browser between sessions.</p></div></div><p><button class="action secondary" onclick="resetProgress()">Reset my progress</button></p></div>`}
function resetProgress(){if(confirm('Reset all saved quiz progress in this browser?')){progress={};save();showProgress()}}
function showAdmin(){stage.innerHTML=`<div class="panel"><h2>Admin</h2><p>Member management will be expanded when the full LA and LC dataset is loaded.</p><p><strong>${members.length}</strong> member record(s) currently available.</p></div>`}
